version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.12.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    
  backend:
    build:
      context: ../.
      dockerfile: deployment/Dockerfile
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db
      - rabbit
    ports:
      - "9999:9999"

  ml-backend:
    build:
      context: ../../ml-backend/.
      dockerfile: Dockerfile
    restart: always
